/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VariantsIndexRouteImport } from './routes/variants/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as VariantsERouteImport } from './routes/variants/e'
import { Route as VariantsDRouteImport } from './routes/variants/d'
import { Route as VariantsCRouteImport } from './routes/variants/c'
import { Route as VariantsBRouteImport } from './routes/variants/b'
import { Route as VariantsARouteImport } from './routes/variants/a'
import { Route as InviteInviteIdRouteImport } from './routes/invite/$inviteId'
import { Route as BlogNewRouteImport } from './routes/blog/new'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppDeveloperRouteImport } from './routes/app/developer'
import { Route as AppProjectIndexRouteImport } from './routes/app/project/index'
import { Route as BlogEditSlugRouteImport } from './routes/blog/edit/$slug'
import { Route as AppProjectProjectIdRouteImport } from './routes/app/project/$projectId'
import { Route as AppCallbacksOauthGoogleRouteImport } from './routes/app/callbacks/oauth/google'
import { Route as AppCallbacksOauthGithubRouteImport } from './routes/app/callbacks/oauth/github'
import { Route as AppCallbacksIntegrationsGithubRouteImport } from './routes/app/callbacks/integrations/github'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantsIndexRoute = VariantsIndexRouteImport.update({
  id: '/variants/',
  path: '/variants/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantsERoute = VariantsERouteImport.update({
  id: '/variants/e',
  path: '/variants/e',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantsDRoute = VariantsDRouteImport.update({
  id: '/variants/d',
  path: '/variants/d',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantsCRoute = VariantsCRouteImport.update({
  id: '/variants/c',
  path: '/variants/c',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantsBRoute = VariantsBRouteImport.update({
  id: '/variants/b',
  path: '/variants/b',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantsARoute = VariantsARouteImport.update({
  id: '/variants/a',
  path: '/variants/a',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInviteIdRoute = InviteInviteIdRouteImport.update({
  id: '/invite/$inviteId',
  path: '/invite/$inviteId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogNewRoute = BlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperRoute = AppDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIndexRoute = AppProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => AppRoute,
} as any)
const BlogEditSlugRoute = BlogEditSlugRouteImport.update({
  id: '/blog/edit/$slug',
  path: '/blog/edit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectProjectIdRoute = AppProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppCallbacksOauthGoogleRoute = AppCallbacksOauthGoogleRouteImport.update({
  id: '/callbacks/oauth/google',
  path: '/callbacks/oauth/google',
  getParentRoute: () => AppRoute,
} as any)
const AppCallbacksOauthGithubRoute = AppCallbacksOauthGithubRouteImport.update({
  id: '/callbacks/oauth/github',
  path: '/callbacks/oauth/github',
  getParentRoute: () => AppRoute,
} as any)
const AppCallbacksIntegrationsGithubRoute =
  AppCallbacksIntegrationsGithubRouteImport.update({
    id: '/callbacks/integrations/github',
    path: '/callbacks/integrations/github',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/developer': typeof AppDeveloperRoute
  '/app/login': typeof AppLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/new': typeof BlogNewRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/variants/a': typeof VariantsARoute
  '/variants/b': typeof VariantsBRoute
  '/variants/c': typeof VariantsCRoute
  '/variants/d': typeof VariantsDRoute
  '/variants/e': typeof VariantsERoute
  '/blog': typeof BlogIndexRoute
  '/variants': typeof VariantsIndexRoute
  '/app/project/$projectId': typeof AppProjectProjectIdRoute
  '/blog/edit/$slug': typeof BlogEditSlugRoute
  '/app/project': typeof AppProjectIndexRoute
  '/app/callbacks/integrations/github': typeof AppCallbacksIntegrationsGithubRoute
  '/app/callbacks/oauth/github': typeof AppCallbacksOauthGithubRoute
  '/app/callbacks/oauth/google': typeof AppCallbacksOauthGoogleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/developer': typeof AppDeveloperRoute
  '/app/login': typeof AppLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/new': typeof BlogNewRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/variants/a': typeof VariantsARoute
  '/variants/b': typeof VariantsBRoute
  '/variants/c': typeof VariantsCRoute
  '/variants/d': typeof VariantsDRoute
  '/variants/e': typeof VariantsERoute
  '/blog': typeof BlogIndexRoute
  '/variants': typeof VariantsIndexRoute
  '/app/project/$projectId': typeof AppProjectProjectIdRoute
  '/blog/edit/$slug': typeof BlogEditSlugRoute
  '/app/project': typeof AppProjectIndexRoute
  '/app/callbacks/integrations/github': typeof AppCallbacksIntegrationsGithubRoute
  '/app/callbacks/oauth/github': typeof AppCallbacksOauthGithubRoute
  '/app/callbacks/oauth/google': typeof AppCallbacksOauthGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/developer': typeof AppDeveloperRoute
  '/app/login': typeof AppLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/new': typeof BlogNewRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/variants/a': typeof VariantsARoute
  '/variants/b': typeof VariantsBRoute
  '/variants/c': typeof VariantsCRoute
  '/variants/d': typeof VariantsDRoute
  '/variants/e': typeof VariantsERoute
  '/blog/': typeof BlogIndexRoute
  '/variants/': typeof VariantsIndexRoute
  '/app/project/$projectId': typeof AppProjectProjectIdRoute
  '/blog/edit/$slug': typeof BlogEditSlugRoute
  '/app/project/': typeof AppProjectIndexRoute
  '/app/callbacks/integrations/github': typeof AppCallbacksIntegrationsGithubRoute
  '/app/callbacks/oauth/github': typeof AppCallbacksOauthGithubRoute
  '/app/callbacks/oauth/google': typeof AppCallbacksOauthGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/developer'
    | '/app/login'
    | '/blog/$slug'
    | '/blog/new'
    | '/invite/$inviteId'
    | '/variants/a'
    | '/variants/b'
    | '/variants/c'
    | '/variants/d'
    | '/variants/e'
    | '/blog'
    | '/variants'
    | '/app/project/$projectId'
    | '/blog/edit/$slug'
    | '/app/project'
    | '/app/callbacks/integrations/github'
    | '/app/callbacks/oauth/github'
    | '/app/callbacks/oauth/google'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/developer'
    | '/app/login'
    | '/blog/$slug'
    | '/blog/new'
    | '/invite/$inviteId'
    | '/variants/a'
    | '/variants/b'
    | '/variants/c'
    | '/variants/d'
    | '/variants/e'
    | '/blog'
    | '/variants'
    | '/app/project/$projectId'
    | '/blog/edit/$slug'
    | '/app/project'
    | '/app/callbacks/integrations/github'
    | '/app/callbacks/oauth/github'
    | '/app/callbacks/oauth/google'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/developer'
    | '/app/login'
    | '/blog/$slug'
    | '/blog/new'
    | '/invite/$inviteId'
    | '/variants/a'
    | '/variants/b'
    | '/variants/c'
    | '/variants/d'
    | '/variants/e'
    | '/blog/'
    | '/variants/'
    | '/app/project/$projectId'
    | '/blog/edit/$slug'
    | '/app/project/'
    | '/app/callbacks/integrations/github'
    | '/app/callbacks/oauth/github'
    | '/app/callbacks/oauth/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  BlogNewRoute: typeof BlogNewRoute
  InviteInviteIdRoute: typeof InviteInviteIdRoute
  VariantsARoute: typeof VariantsARoute
  VariantsBRoute: typeof VariantsBRoute
  VariantsCRoute: typeof VariantsCRoute
  VariantsDRoute: typeof VariantsDRoute
  VariantsERoute: typeof VariantsERoute
  BlogIndexRoute: typeof BlogIndexRoute
  VariantsIndexRoute: typeof VariantsIndexRoute
  BlogEditSlugRoute: typeof BlogEditSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variants/': {
      id: '/variants/'
      path: '/variants'
      fullPath: '/variants'
      preLoaderRoute: typeof VariantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variants/e': {
      id: '/variants/e'
      path: '/variants/e'
      fullPath: '/variants/e'
      preLoaderRoute: typeof VariantsERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variants/d': {
      id: '/variants/d'
      path: '/variants/d'
      fullPath: '/variants/d'
      preLoaderRoute: typeof VariantsDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variants/c': {
      id: '/variants/c'
      path: '/variants/c'
      fullPath: '/variants/c'
      preLoaderRoute: typeof VariantsCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variants/b': {
      id: '/variants/b'
      path: '/variants/b'
      fullPath: '/variants/b'
      preLoaderRoute: typeof VariantsBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variants/a': {
      id: '/variants/a'
      path: '/variants/a'
      fullPath: '/variants/a'
      preLoaderRoute: typeof VariantsARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$inviteId': {
      id: '/invite/$inviteId'
      path: '/invite/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof InviteInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/new': {
      id: '/blog/new'
      path: '/blog/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof BlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/developer': {
      id: '/app/developer'
      path: '/developer'
      fullPath: '/app/developer'
      preLoaderRoute: typeof AppDeveloperRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/project/': {
      id: '/app/project/'
      path: '/project'
      fullPath: '/app/project'
      preLoaderRoute: typeof AppProjectIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/blog/edit/$slug': {
      id: '/blog/edit/$slug'
      path: '/blog/edit/$slug'
      fullPath: '/blog/edit/$slug'
      preLoaderRoute: typeof BlogEditSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/project/$projectId': {
      id: '/app/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/app/project/$projectId'
      preLoaderRoute: typeof AppProjectProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/callbacks/oauth/google': {
      id: '/app/callbacks/oauth/google'
      path: '/callbacks/oauth/google'
      fullPath: '/app/callbacks/oauth/google'
      preLoaderRoute: typeof AppCallbacksOauthGoogleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/callbacks/oauth/github': {
      id: '/app/callbacks/oauth/github'
      path: '/callbacks/oauth/github'
      fullPath: '/app/callbacks/oauth/github'
      preLoaderRoute: typeof AppCallbacksOauthGithubRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/callbacks/integrations/github': {
      id: '/app/callbacks/integrations/github'
      path: '/callbacks/integrations/github'
      fullPath: '/app/callbacks/integrations/github'
      preLoaderRoute: typeof AppCallbacksIntegrationsGithubRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDeveloperRoute: typeof AppDeveloperRoute
  AppLoginRoute: typeof AppLoginRoute
  AppProjectProjectIdRoute: typeof AppProjectProjectIdRoute
  AppProjectIndexRoute: typeof AppProjectIndexRoute
  AppCallbacksIntegrationsGithubRoute: typeof AppCallbacksIntegrationsGithubRoute
  AppCallbacksOauthGithubRoute: typeof AppCallbacksOauthGithubRoute
  AppCallbacksOauthGoogleRoute: typeof AppCallbacksOauthGoogleRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDeveloperRoute: AppDeveloperRoute,
  AppLoginRoute: AppLoginRoute,
  AppProjectProjectIdRoute: AppProjectProjectIdRoute,
  AppProjectIndexRoute: AppProjectIndexRoute,
  AppCallbacksIntegrationsGithubRoute: AppCallbacksIntegrationsGithubRoute,
  AppCallbacksOauthGithubRoute: AppCallbacksOauthGithubRoute,
  AppCallbacksOauthGoogleRoute: AppCallbacksOauthGoogleRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  BlogNewRoute: BlogNewRoute,
  InviteInviteIdRoute: InviteInviteIdRoute,
  VariantsARoute: VariantsARoute,
  VariantsBRoute: VariantsBRoute,
  VariantsCRoute: VariantsCRoute,
  VariantsDRoute: VariantsDRoute,
  VariantsERoute: VariantsERoute,
  BlogIndexRoute: BlogIndexRoute,
  VariantsIndexRoute: VariantsIndexRoute,
  BlogEditSlugRoute: BlogEditSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
