// Generated by kea-typegen on Tue, 14 Apr 2026 23:02:22 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { IntegrationsLogicProps, SuggestedRepo } from './integrationsLogic'
import type { DecryptedProject } from './projectLogic'
import type { Installation, Integration, Repository } from '../api/integrations.api'
import type { RepoWithInstallation } from './suggestedProjectsLogic'

export interface integrationsLogicType extends Logic {
    actionCreators: {
        setIntegrations: (integrations: Integration[]) => ({
            type: "set integrations (src.lib.logics.integrationsLogic)";
            payload: {
                integrations: Integration[];
            };
        });
        loadProjectData: () => ({
            type: "load project data (src.lib.logics.integrationsLogic)";
            payload: any;
        });
        removeInstallationFromProject: () => ({
            type: "remove installation from project (src.lib.logics.integrationsLogic)";
            payload: {
                value: true;
            };
        });
        loadRepositories: () => ({
            type: "load repositories (src.lib.logics.integrationsLogic)";
            payload: {
                value: true;
            };
        });
        loadIntegrations: () => ({
            type: "load integrations (src.lib.logics.integrationsLogic)";
            payload: {
                value: true;
            };
        });
        createIntegration: (repositoryId: number, installationEntityId: string) => ({
            type: "create integration (src.lib.logics.integrationsLogic)";
            payload: {
                installationEntityId: string;
                repositoryId: number;
            };
        });
        removeIntegration: (integrationId: string) => ({
            type: "remove integration (src.lib.logics.integrationsLogic)";
            payload: {
                integrationId: string;
            };
        });
        setRepositories: (repositories: Repository[]) => ({
            type: "set repositories (src.lib.logics.integrationsLogic)";
            payload: {
                repositories: Repository[];
            };
        });
        setLocalIntegrations: (integrations: Integration[]) => ({
            type: "set local integrations (src.lib.logics.integrationsLogic)";
            payload: {
                integrations: Integration[];
            };
        });
        setSelectedInstallationEntityId: (installationEntityId: string) => ({
            type: "set selected installation entity id (src.lib.logics.integrationsLogic)";
            payload: {
                installationEntityId: string;
            };
        });
        loadRepositoriesSuccess: (repositories: Repository[], payload?: {
            value: true;
        }) => ({
            type: "load repositories success (src.lib.logics.integrationsLogic)";
            payload: {
                repositories: Repository[];
                payload?: {
                    value: true;
                };
            };
        });
        loadRepositoriesFailure: (error: string, errorObject?: any) => ({
            type: "load repositories failure (src.lib.logics.integrationsLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        loadIntegrationsSuccess: (integrations: Integration[], payload?: {
            value: true;
        }) => ({
            type: "load integrations success (src.lib.logics.integrationsLogic)";
            payload: {
                integrations: Integration[];
                payload?: {
                    value: true;
                };
            };
        });
        loadIntegrationsFailure: (error: string, errorObject?: any) => ({
            type: "load integrations failure (src.lib.logics.integrationsLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "set integrations (src.lib.logics.integrationsLogic)": "setIntegrations";
        "load project data (src.lib.logics.integrationsLogic)": "loadProjectData";
        "remove installation from project (src.lib.logics.integrationsLogic)": "removeInstallationFromProject";
        "load repositories (src.lib.logics.integrationsLogic)": "loadRepositories";
        "load integrations (src.lib.logics.integrationsLogic)": "loadIntegrations";
        "create integration (src.lib.logics.integrationsLogic)": "createIntegration";
        "remove integration (src.lib.logics.integrationsLogic)": "removeIntegration";
        "set repositories (src.lib.logics.integrationsLogic)": "setRepositories";
        "set local integrations (src.lib.logics.integrationsLogic)": "setLocalIntegrations";
        "set selected installation entity id (src.lib.logics.integrationsLogic)": "setSelectedInstallationEntityId";
        "load repositories success (src.lib.logics.integrationsLogic)": "loadRepositoriesSuccess";
        "load repositories failure (src.lib.logics.integrationsLogic)": "loadRepositoriesFailure";
        "load integrations success (src.lib.logics.integrationsLogic)": "loadIntegrationsSuccess";
        "load integrations failure (src.lib.logics.integrationsLogic)": "loadIntegrationsFailure";
    };
    actionTypes: {
        setIntegrations: "set integrations (src.lib.logics.integrationsLogic)";
        loadProjectData: "load project data (src.lib.logics.integrationsLogic)";
        removeInstallationFromProject: "remove installation from project (src.lib.logics.integrationsLogic)";
        loadRepositories: "load repositories (src.lib.logics.integrationsLogic)";
        loadIntegrations: "load integrations (src.lib.logics.integrationsLogic)";
        createIntegration: "create integration (src.lib.logics.integrationsLogic)";
        removeIntegration: "remove integration (src.lib.logics.integrationsLogic)";
        setRepositories: "set repositories (src.lib.logics.integrationsLogic)";
        setLocalIntegrations: "set local integrations (src.lib.logics.integrationsLogic)";
        setSelectedInstallationEntityId: "set selected installation entity id (src.lib.logics.integrationsLogic)";
        loadRepositoriesSuccess: "load repositories success (src.lib.logics.integrationsLogic)";
        loadRepositoriesFailure: "load repositories failure (src.lib.logics.integrationsLogic)";
        loadIntegrationsSuccess: "load integrations success (src.lib.logics.integrationsLogic)";
        loadIntegrationsFailure: "load integrations failure (src.lib.logics.integrationsLogic)";
    };
    actions: {
        setIntegrations: (integrations: Integration[]) => void;
        loadProjectData: () => void;
        removeInstallationFromProject: () => void;
        loadRepositories: () => void;
        loadIntegrations: () => void;
        createIntegration: (repositoryId: number, installationEntityId: string) => void;
        removeIntegration: (integrationId: string) => void;
        setRepositories: (repositories: Repository[]) => void;
        setLocalIntegrations: (integrations: Integration[]) => void;
        setSelectedInstallationEntityId: (installationEntityId: string) => void;
        loadRepositoriesSuccess: (repositories: Repository[], payload?: {
            value: true;
        }) => void;
        loadRepositoriesFailure: (error: string, errorObject?: any) => void;
        loadIntegrationsSuccess: (integrations: Integration[], payload?: {
            value: true;
        }) => void;
        loadIntegrationsFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        setIntegrations: (integrations: Integration[]) => Promise<any>;
        loadProjectData: () => Promise<any>;
        removeInstallationFromProject: () => Promise<any>;
        loadRepositories: () => Promise<any>;
        loadIntegrations: () => Promise<any>;
        createIntegration: (repositoryId: number, installationEntityId: string) => Promise<any>;
        removeIntegration: (integrationId: string) => Promise<any>;
        setRepositories: (repositories: Repository[]) => Promise<any>;
        setLocalIntegrations: (integrations: Integration[]) => Promise<any>;
        setSelectedInstallationEntityId: (installationEntityId: string) => Promise<any>;
        loadRepositoriesSuccess: (repositories: Repository[], payload?: {
            value: true;
        }) => Promise<any>;
        loadRepositoriesFailure: (error: string, errorObject?: any) => Promise<any>;
        loadIntegrationsSuccess: (integrations: Integration[], payload?: {
            value: true;
        }) => Promise<any>;
        loadIntegrationsFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        repositories: Repository[];
        integrations: Integration[];
        installation: Installation | null;
        selectedInstallationEntityId: string | null;
        repositoriesLoading: boolean;
        integrationsLoading: boolean;
    };
    events: {
        afterMount: () => void;
    };
    key: string;
    listeners: {
        "createIntegration": ((action: {
            type: "create integration (src.lib.logics.integrationsLogic)";
            payload: {
                installationEntityId: string;
                repositoryId: number;
            };
        }, previousState: any) => void | Promise<void>)[];
        "removeIntegration": ((action: {
            type: "remove integration (src.lib.logics.integrationsLogic)";
            payload: {
                integrationId: string;
            };
        }, previousState: any) => void | Promise<void>)[];
        "removeInstallationFromProject": ((action: {
            type: "remove installation from project (src.lib.logics.integrationsLogic)";
            payload: {
                value: true;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "src",
        "lib",
        "logics",
        "integrationsLogic"
    ];
    pathString: "src.lib.logics.integrationsLogic";
    props: IntegrationsLogicProps;
    reducer: (state: any, action: any, fullState: any) => {
        repositories: Repository[];
        integrations: Integration[];
        installation: Installation | null;
        selectedInstallationEntityId: string | null;
        repositoriesLoading: boolean;
        integrationsLoading: boolean;
    };
    reducers: {
        repositories: (state: Repository[], action: any, fullState: any) => Repository[];
        integrations: (state: Integration[], action: any, fullState: any) => Integration[];
        installation: (state: Installation | null, action: any, fullState: any) => Installation | null;
        selectedInstallationEntityId: (state: string | null, action: any, fullState: any) => string | null;
        repositoriesLoading: (state: boolean, action: any, fullState: any) => boolean;
        integrationsLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        repositories: Repository[];
        integrations: Integration[];
        installation: Installation | null;
        selectedInstallationEntityId: string | null;
        repositoriesLoading: boolean;
        integrationsLoading: boolean;
    };
    selectors: {
        repositories: (state: any, props?: any) => Repository[];
        integrations: (state: any, props?: any) => Integration[];
        installation: (state: any, props?: any) => Installation | null;
        selectedInstallationEntityId: (state: any, props?: any) => string | null;
        repositoriesLoading: (state: any, props?: any) => boolean;
        integrationsLoading: (state: any, props?: any) => boolean;
        jwtToken: (state: any, props?: any) => string | null;
        projectData: (state: any, props?: any) => DecryptedProject | null;
        installations: (state: any, props?: any) => Installation[];
        allRepositories: (state: any, props?: any) => RepoWithInstallation[];
        loading: (state: any, props?: any) => boolean;
        githubInstallationId: (state: any, props?: any) => number;
        suggestedIntegrations: (state: any, props?: any) => SuggestedRepo[];
        installationsLoading: (state: any, props?: any) => boolean;
        allRepositoriesLoading: (state: any, props?: any) => boolean;
    };
    sharedListeners: {};
    values: {
        repositories: Repository[];
        integrations: Integration[];
        installation: Installation | null;
        selectedInstallationEntityId: string | null;
        repositoriesLoading: boolean;
        integrationsLoading: boolean;
        jwtToken: string | null;
        projectData: DecryptedProject | null;
        installations: Installation[];
        allRepositories: RepoWithInstallation[];
        loading: boolean;
        githubInstallationId: number;
        suggestedIntegrations: SuggestedRepo[];
        installationsLoading: boolean;
        allRepositoriesLoading: boolean;
    };
    _isKea: true;
    _isKeaWithKey: true;
    __keaTypeGenInternalSelectorTypes: {
        githubInstallationId: (projectData: DecryptedProject | null) => number;
        suggestedIntegrations: (allRepositories: RepoWithInstallation[], integrations: Integration[], projectData: DecryptedProject | null) => SuggestedRepo[];
        installationsLoading: (loading: boolean) => boolean;
        allRepositoriesLoading: (loading: boolean) => boolean;
    };
}