// Generated by kea-typegen on Sat, 25 Apr 2026 07:33:44 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { User } from '../api/user.api'

export interface keyLogicType extends Logic {
    actionCreators: {
        loadUserData: () => ({
            type: "load user data (src.lib.logics.keyLogic)";
            payload: any;
        });
        queueFTUX: () => ({
            type: "queue f t u x (src.lib.logics.keyLogic)";
            payload: {
                value: true;
            };
        });
        setHasMasterKey: (hasMasterKey: boolean) => ({
            type: "set has master key (src.lib.logics.keyLogic)";
            payload: {
                hasMasterKey: boolean;
            };
        });
        hydrateMasterKey: () => ({
            type: "hydrate master key (src.lib.logics.keyLogic)";
            payload: {
                value: true;
            };
        });
        setUpPassphrase: (passphrase: string) => ({
            type: "set up passphrase (src.lib.logics.keyLogic)";
            payload: {
                passphrase: string;
            };
        });
        unlock: (passphrase: string) => ({
            type: "unlock (src.lib.logics.keyLogic)";
            payload: {
                passphrase: string;
            };
        });
        reset: () => ({
            type: "reset (src.lib.logics.keyLogic)";
            payload: {
                value: true;
            };
        });
    };
    actionKeys: {
        "load user data (src.lib.logics.keyLogic)": "loadUserData";
        "queue f t u x (src.lib.logics.keyLogic)": "queueFTUX";
        "set has master key (src.lib.logics.keyLogic)": "setHasMasterKey";
        "hydrate master key (src.lib.logics.keyLogic)": "hydrateMasterKey";
        "set up passphrase (src.lib.logics.keyLogic)": "setUpPassphrase";
        "unlock (src.lib.logics.keyLogic)": "unlock";
        "reset (src.lib.logics.keyLogic)": "reset";
    };
    actionTypes: {
        loadUserData: "load user data (src.lib.logics.keyLogic)";
        queueFTUX: "queue f t u x (src.lib.logics.keyLogic)";
        setHasMasterKey: "set has master key (src.lib.logics.keyLogic)";
        hydrateMasterKey: "hydrate master key (src.lib.logics.keyLogic)";
        setUpPassphrase: "set up passphrase (src.lib.logics.keyLogic)";
        unlock: "unlock (src.lib.logics.keyLogic)";
        reset: "reset (src.lib.logics.keyLogic)";
    };
    actions: {
        loadUserData: () => void;
        queueFTUX: () => void;
        setHasMasterKey: (hasMasterKey: boolean) => void;
        hydrateMasterKey: () => void;
        setUpPassphrase: (passphrase: string) => void;
        unlock: (passphrase: string) => void;
        reset: () => void;
    };
    asyncActions: {
        loadUserData: () => Promise<any>;
        queueFTUX: () => Promise<any>;
        setHasMasterKey: (hasMasterKey: boolean) => Promise<any>;
        hydrateMasterKey: () => Promise<any>;
        setUpPassphrase: (passphrase: string) => Promise<any>;
        unlock: (passphrase: string) => Promise<any>;
        reset: () => Promise<any>;
    };
    defaults: {
        hasMasterKey: boolean;
    };
    events: {
        afterMount: () => void;
    };
    key: undefined;
    listeners: {
        "setUpPassphrase": ((action: {
            type: "set up passphrase (src.lib.logics.keyLogic)";
            payload: {
                passphrase: string;
            };
        }, previousState: any) => void | Promise<void>)[];
        "unlock": ((action: {
            type: "unlock (src.lib.logics.keyLogic)";
            payload: {
                passphrase: string;
            };
        }, previousState: any) => void | Promise<void>)[];
        "reset": ((action: {
            type: "reset (src.lib.logics.keyLogic)";
            payload: {
                value: true;
            };
        }, previousState: any) => void | Promise<void>)[];
        "hydrateMasterKey": ((action: {
            type: "hydrate master key (src.lib.logics.keyLogic)";
            payload: {
                value: true;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "src",
        "lib",
        "logics",
        "keyLogic"
    ];
    pathString: "src.lib.logics.keyLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        hasMasterKey: boolean;
    };
    reducers: {
        hasMasterKey: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        hasMasterKey: boolean;
    };
    selectors: {
        hasMasterKey: (state: any, props?: any) => boolean;
        userData: (state: any, props?: any) => User | null;
        jwtToken: (state: any, props?: any) => string | null;
        shouldSetUpPassphrase: (state: any, props?: any) => boolean;
        keysAreSetUp: (state: any, props?: any) => boolean;
        browserIsUnlocked: (state: any, props?: any) => boolean;
    };
    sharedListeners: {};
    values: {
        hasMasterKey: boolean;
        userData: User | null;
        jwtToken: string | null;
        shouldSetUpPassphrase: boolean;
        keysAreSetUp: boolean;
        browserIsUnlocked: boolean;
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        shouldSetUpPassphrase: (userData: User | null) => boolean;
        keysAreSetUp: (userData: User | null) => boolean;
        browserIsUnlocked: (hasMasterKey: boolean) => boolean;
    };
}