// Generated by kea-typegen on Tue, 14 Oct 2025 16:55:49 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { PersonalInvitationsLogicProps } from './personalInvitationsLogic'
import type { DecryptedProject } from './projectLogic'
import type { PersonalInvitation } from '../api/personal-invitations.api'

export interface personalInvitationsLogicType extends Logic {
    actionCreators: {
        deletePersonalInvitation: (invitationId: string) => ({
            type: "delete personal invitation (src.lib.logics.personalInvitationsLogic)";
            payload: {
                invitationId: string;
            };
        });
        loadPersonalInvitations: () => ({
            type: "load personal invitations (src.lib.logics.personalInvitationsLogic)";
            payload: any;
        });
        loadPersonalInvitationsSuccess: (personalInvitations: PersonalInvitation[], payload?: any) => ({
            type: "load personal invitations success (src.lib.logics.personalInvitationsLogic)";
            payload: {
                personalInvitations: PersonalInvitation[];
                payload?: any;
            };
        });
        loadPersonalInvitationsFailure: (error: string, errorObject?: any) => ({
            type: "load personal invitations failure (src.lib.logics.personalInvitationsLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "delete personal invitation (src.lib.logics.personalInvitationsLogic)": "deletePersonalInvitation";
        "load personal invitations (src.lib.logics.personalInvitationsLogic)": "loadPersonalInvitations";
        "load personal invitations success (src.lib.logics.personalInvitationsLogic)": "loadPersonalInvitationsSuccess";
        "load personal invitations failure (src.lib.logics.personalInvitationsLogic)": "loadPersonalInvitationsFailure";
    };
    actionTypes: {
        deletePersonalInvitation: "delete personal invitation (src.lib.logics.personalInvitationsLogic)";
        loadPersonalInvitations: "load personal invitations (src.lib.logics.personalInvitationsLogic)";
        loadPersonalInvitationsSuccess: "load personal invitations success (src.lib.logics.personalInvitationsLogic)";
        loadPersonalInvitationsFailure: "load personal invitations failure (src.lib.logics.personalInvitationsLogic)";
    };
    actions: {
        deletePersonalInvitation: (invitationId: string) => void;
        loadPersonalInvitations: () => void;
        loadPersonalInvitationsSuccess: (personalInvitations: PersonalInvitation[], payload?: any) => void;
        loadPersonalInvitationsFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        deletePersonalInvitation: (invitationId: string) => Promise<any>;
        loadPersonalInvitations: () => Promise<any>;
        loadPersonalInvitationsSuccess: (personalInvitations: PersonalInvitation[], payload?: any) => Promise<any>;
        loadPersonalInvitationsFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        personalInvitations: PersonalInvitation[];
        personalInvitationsLoading: boolean;
    };
    events: {};
    key: string;
    listeners: {
        "deletePersonalInvitation": ((action: {
            type: "delete personal invitation (src.lib.logics.personalInvitationsLogic)";
            payload: {
                invitationId: string;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "src",
        "lib",
        "logics",
        "personalInvitationsLogic"
    ];
    pathString: "src.lib.logics.personalInvitationsLogic";
    props: PersonalInvitationsLogicProps;
    reducer: (state: any, action: any, fullState: any) => {
        personalInvitations: PersonalInvitation[];
        personalInvitationsLoading: boolean;
    };
    reducers: {
        personalInvitations: (state: PersonalInvitation[], action: any, fullState: any) => PersonalInvitation[];
        personalInvitationsLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        personalInvitations: PersonalInvitation[];
        personalInvitationsLoading: boolean;
    };
    selectors: {
        personalInvitations: (state: any, props?: any) => PersonalInvitation[];
        personalInvitationsLoading: (state: any, props?: any) => boolean;
        jwtToken: (state: any, props?: any) => string | null;
        projectData: (state: any, props?: any) => DecryptedProject | null;
    };
    sharedListeners: {};
    values: {
        personalInvitations: PersonalInvitation[];
        personalInvitationsLoading: boolean;
        jwtToken: string | null;
        projectData: DecryptedProject | null;
    };
    _isKea: true;
    _isKeaWithKey: true;
}