// Generated by kea-typegen on Thu, 16 Oct 2025 15:25:09 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { User } from '../api/user.api'
import type { Project } from '../api/projects.api'

export interface projectsLogicType extends Logic {
    actionCreators: {
        addProject: (project: {
            name: string;
        }, navigateCallback?: (projectId: string) => void) => ({
            type: "add project (src.lib.logics.projectsLogic)";
            payload: {
                navigateCallback: ((projectId: string) => void) | undefined;
                project: {
                    name: string;
                };
            };
        });
        readProjectById: (projectId: string) => ({
            type: "read project by id (src.lib.logics.projectsLogic)";
            payload: {
                projectId: string;
            };
        });
        loadProjects: () => ({
            type: "load projects (src.lib.logics.projectsLogic)";
            payload: {
                value: true;
            };
        });
        deleteProject: (projectId: string) => ({
            type: "delete project (src.lib.logics.projectsLogic)";
            payload: {
                projectId: string;
            };
        });
        reorderProjects: (projects: Project[]) => ({
            type: "reorder projects (src.lib.logics.projectsLogic)";
            payload: {
                projects: Project[];
            };
        });
        setProjectOrder: (projectIds: string[]) => ({
            type: "set project order (src.lib.logics.projectsLogic)";
            payload: {
                projectIds: string[];
            };
        });
        loadProjectsSuccess: (projects: Project[], payload?: {
            value: true;
        }) => ({
            type: "load projects success (src.lib.logics.projectsLogic)";
            payload: {
                projects: Project[];
                payload?: {
                    value: true;
                };
            };
        });
        loadProjectsFailure: (error: string, errorObject?: any) => ({
            type: "load projects failure (src.lib.logics.projectsLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "add project (src.lib.logics.projectsLogic)": "addProject";
        "read project by id (src.lib.logics.projectsLogic)": "readProjectById";
        "load projects (src.lib.logics.projectsLogic)": "loadProjects";
        "delete project (src.lib.logics.projectsLogic)": "deleteProject";
        "reorder projects (src.lib.logics.projectsLogic)": "reorderProjects";
        "set project order (src.lib.logics.projectsLogic)": "setProjectOrder";
        "load projects success (src.lib.logics.projectsLogic)": "loadProjectsSuccess";
        "load projects failure (src.lib.logics.projectsLogic)": "loadProjectsFailure";
    };
    actionTypes: {
        addProject: "add project (src.lib.logics.projectsLogic)";
        readProjectById: "read project by id (src.lib.logics.projectsLogic)";
        loadProjects: "load projects (src.lib.logics.projectsLogic)";
        deleteProject: "delete project (src.lib.logics.projectsLogic)";
        reorderProjects: "reorder projects (src.lib.logics.projectsLogic)";
        setProjectOrder: "set project order (src.lib.logics.projectsLogic)";
        loadProjectsSuccess: "load projects success (src.lib.logics.projectsLogic)";
        loadProjectsFailure: "load projects failure (src.lib.logics.projectsLogic)";
    };
    actions: {
        addProject: (project: {
            name: string;
        }, navigateCallback?: (projectId: string) => void) => void;
        readProjectById: (projectId: string) => void;
        loadProjects: () => void;
        deleteProject: (projectId: string) => void;
        reorderProjects: (projects: Project[]) => void;
        setProjectOrder: (projectIds: string[]) => void;
        loadProjectsSuccess: (projects: Project[], payload?: {
            value: true;
        }) => void;
        loadProjectsFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        addProject: (project: {
            name: string;
        }, navigateCallback?: (projectId: string) => void) => Promise<any>;
        readProjectById: (projectId: string) => Promise<any>;
        loadProjects: () => Promise<any>;
        deleteProject: (projectId: string) => Promise<any>;
        reorderProjects: (projects: Project[]) => Promise<any>;
        setProjectOrder: (projectIds: string[]) => Promise<any>;
        loadProjectsSuccess: (projects: Project[], payload?: {
            value: true;
        }) => Promise<any>;
        loadProjectsFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        projects: Project[] | undefined;
        projectsLoading: boolean;
        projectOrder: string[];
    };
    events: {};
    key: undefined;
    listeners: {
        "addProject": ((action: {
            type: "add project (src.lib.logics.projectsLogic)";
            payload: {
                navigateCallback: ((projectId: string) => void) | undefined;
                project: {
                    name: string;
                };
            };
        }, previousState: any) => void | Promise<void>)[];
        "deleteProject": ((action: {
            type: "delete project (src.lib.logics.projectsLogic)";
            payload: {
                projectId: string;
            };
        }, previousState: any) => void | Promise<void>)[];
        "reorderProjects": ((action: {
            type: "reorder projects (src.lib.logics.projectsLogic)";
            payload: {
                projects: Project[];
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "src",
        "lib",
        "logics",
        "projectsLogic"
    ];
    pathString: "src.lib.logics.projectsLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        projects: Project[] | undefined;
        projectsLoading: boolean;
        projectOrder: string[];
    };
    reducers: {
        projects: (state: Project[] | undefined, action: any, fullState: any) => Project[] | undefined;
        projectsLoading: (state: boolean, action: any, fullState: any) => boolean;
        projectOrder: (state: string[], action: any, fullState: any) => string[];
    };
    selector: (state: any) => {
        projects: Project[] | undefined;
        projectsLoading: boolean;
        projectOrder: string[];
    };
    selectors: {
        projects: (state: any, props?: any) => Project[] | undefined;
        projectsLoading: (state: any, props?: any) => boolean;
        projectOrder: (state: any, props?: any) => string[];
        userData: (state: any, props?: any) => User | null;
        jwtToken: (state: any, props?: any) => string | null;
        readProjectById: (state: any, props?: any) => (id: string) => Project | undefined;
        sortedProjects: (state: any, props?: any) => Project[] | undefined;
    };
    sharedListeners: {};
    values: {
        projects: Project[] | undefined;
        projectsLoading: boolean;
        projectOrder: string[];
        userData: User | null;
        jwtToken: string | null;
        readProjectById: (id: string) => Project | undefined;
        sortedProjects: Project[] | undefined;
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        readProjectById: (projects: Project[] | undefined) => (id: string) => Project | undefined;
        sortedProjects: (projects: Project[] | undefined, projectOrder: string[]) => Project[] | undefined;
    };
}