// Generated by kea-typegen on Mon, 20 Apr 2026 07:59:33 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { User } from '../api/user.api'
import type { Project } from '../api/projects.api'
import type { Installation } from '../api/integrations.api'
import type { RepoWithInstallation } from './suggestedProjectsLogic'

export interface suggestedProjectsLogicType extends Logic {
    actionCreators: {
        loadSuggestions: () => ({
            type: "load suggestions (src.lib.logics.suggestedProjectsLogic)";
            payload: {
                value: true;
            };
        });
        setInstallations: (installations: Installation[]) => ({
            type: "set installations (src.lib.logics.suggestedProjectsLogic)";
            payload: {
                installations: Installation[];
            };
        });
        setAllRepositories: (allRepositories: RepoWithInstallation[]) => ({
            type: "set all repositories (src.lib.logics.suggestedProjectsLogic)";
            payload: {
                allRepositories: RepoWithInstallation[];
            };
        });
        setLoading: (loading: boolean) => ({
            type: "set loading (src.lib.logics.suggestedProjectsLogic)";
            payload: {
                loading: boolean;
            };
        });
        acceptSuggestion: (repo: RepoWithInstallation, securityLevel: string, navigateCallback?: (projectId: string) => void) => ({
            type: "accept suggestion (src.lib.logics.suggestedProjectsLogic)";
            payload: {
                navigateCallback: ((projectId: string) => void) | undefined;
                repo: RepoWithInstallation;
                securityLevel: string;
            };
        });
        setAcceptingRepoId: (repoId: number | null) => ({
            type: "set accepting repo id (src.lib.logics.suggestedProjectsLogic)";
            payload: {
                repoId: number | null;
            };
        });
        dismissSuggestion: (repoId: number) => ({
            type: "dismiss suggestion (src.lib.logics.suggestedProjectsLogic)";
            payload: {
                repoId: number;
            };
        });
    };
    actionKeys: {
        "load suggestions (src.lib.logics.suggestedProjectsLogic)": "loadSuggestions";
        "set installations (src.lib.logics.suggestedProjectsLogic)": "setInstallations";
        "set all repositories (src.lib.logics.suggestedProjectsLogic)": "setAllRepositories";
        "set loading (src.lib.logics.suggestedProjectsLogic)": "setLoading";
        "accept suggestion (src.lib.logics.suggestedProjectsLogic)": "acceptSuggestion";
        "set accepting repo id (src.lib.logics.suggestedProjectsLogic)": "setAcceptingRepoId";
        "dismiss suggestion (src.lib.logics.suggestedProjectsLogic)": "dismissSuggestion";
    };
    actionTypes: {
        loadSuggestions: "load suggestions (src.lib.logics.suggestedProjectsLogic)";
        setInstallations: "set installations (src.lib.logics.suggestedProjectsLogic)";
        setAllRepositories: "set all repositories (src.lib.logics.suggestedProjectsLogic)";
        setLoading: "set loading (src.lib.logics.suggestedProjectsLogic)";
        acceptSuggestion: "accept suggestion (src.lib.logics.suggestedProjectsLogic)";
        setAcceptingRepoId: "set accepting repo id (src.lib.logics.suggestedProjectsLogic)";
        dismissSuggestion: "dismiss suggestion (src.lib.logics.suggestedProjectsLogic)";
    };
    actions: {
        loadSuggestions: () => void;
        setInstallations: (installations: Installation[]) => void;
        setAllRepositories: (allRepositories: RepoWithInstallation[]) => void;
        setLoading: (loading: boolean) => void;
        acceptSuggestion: (repo: RepoWithInstallation, securityLevel: string, navigateCallback?: (projectId: string) => void) => void;
        setAcceptingRepoId: (repoId: number | null) => void;
        dismissSuggestion: (repoId: number) => void;
    };
    asyncActions: {
        loadSuggestions: () => Promise<any>;
        setInstallations: (installations: Installation[]) => Promise<any>;
        setAllRepositories: (allRepositories: RepoWithInstallation[]) => Promise<any>;
        setLoading: (loading: boolean) => Promise<any>;
        acceptSuggestion: (repo: RepoWithInstallation, securityLevel: string, navigateCallback?: (projectId: string) => void) => Promise<any>;
        setAcceptingRepoId: (repoId: number | null) => Promise<any>;
        dismissSuggestion: (repoId: number) => Promise<any>;
    };
    defaults: {
        installations: Installation[];
        allRepositories: RepoWithInstallation[];
        loading: boolean;
        acceptingRepoId: number | null;
        dismissedRepoIds: number[];
    };
    events: {};
    key: undefined;
    listeners: {
        "loadSuggestions": ((action: {
            type: "load suggestions (src.lib.logics.suggestedProjectsLogic)";
            payload: {
                value: true;
            };
        }, previousState: any) => void | Promise<void>)[];
        "acceptSuggestion": ((action: {
            type: "accept suggestion (src.lib.logics.suggestedProjectsLogic)";
            payload: {
                navigateCallback: ((projectId: string) => void) | undefined;
                repo: RepoWithInstallation;
                securityLevel: string;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "src",
        "lib",
        "logics",
        "suggestedProjectsLogic"
    ];
    pathString: "src.lib.logics.suggestedProjectsLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        installations: Installation[];
        allRepositories: RepoWithInstallation[];
        loading: boolean;
        acceptingRepoId: number | null;
        dismissedRepoIds: number[];
    };
    reducers: {
        installations: (state: Installation[], action: any, fullState: any) => Installation[];
        allRepositories: (state: RepoWithInstallation[], action: any, fullState: any) => RepoWithInstallation[];
        loading: (state: boolean, action: any, fullState: any) => boolean;
        acceptingRepoId: (state: number | null, action: any, fullState: any) => number | null;
        dismissedRepoIds: (state: number[], action: any, fullState: any) => number[];
    };
    selector: (state: any) => {
        installations: Installation[];
        allRepositories: RepoWithInstallation[];
        loading: boolean;
        acceptingRepoId: number | null;
        dismissedRepoIds: number[];
    };
    selectors: {
        installations: (state: any, props?: any) => Installation[];
        allRepositories: (state: any, props?: any) => RepoWithInstallation[];
        loading: (state: any, props?: any) => boolean;
        acceptingRepoId: (state: any, props?: any) => number | null;
        dismissedRepoIds: (state: any, props?: any) => number[];
        userData: (state: any, props?: any) => User | null;
        jwtToken: (state: any, props?: any) => string | null;
        projects: (state: any, props?: any) => Project[] | undefined;
        suggestedProjects: (state: any, props?: any) => RepoWithInstallation[];
        hasInstallations: (state: any, props?: any) => boolean;
    };
    sharedListeners: {};
    values: {
        installations: Installation[];
        allRepositories: RepoWithInstallation[];
        loading: boolean;
        acceptingRepoId: number | null;
        dismissedRepoIds: number[];
        userData: User | null;
        jwtToken: string | null;
        projects: Project[] | undefined;
        suggestedProjects: RepoWithInstallation[];
        hasInstallations: boolean;
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        suggestedProjects: (allRepositories: any, projects: any, dismissedRepoIds: any) => RepoWithInstallation[];
        hasInstallations: (installations: any) => boolean;
    };
}