/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserCoreController_readCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UserCoreController_updateUser"];
        trace?: never;
    };
    "/users/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["UserCoreController_deleteKeys"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/public-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UserCoreController_getPublicKeys"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectCoreController_streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectCoreController_findUserProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/projects/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectCoreController_findUserProjectsForSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProjectCoreController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectCoreController_findById"];
        put?: never;
        post?: never;
        delete: operations["ProjectCoreController_delete"];
        options?: never;
        head?: never;
        patch: operations["ProjectCoreController_update"];
        trace?: never;
    };
    "/projects/{projectId}/suggested-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectCoreController_getSuggestedUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectCoreController_findHistoryById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/encrypted-secrets-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProjectCoreController_addEncryptedSecretsKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ProjectCoreController_removeMember"];
        options?: never;
        head?: never;
        patch: operations["ProjectCoreController_updateMemberRole"];
        trace?: never;
    };
    "/projects/{projectId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InvitationCoreController_findProjectInvitations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InvitationCoreController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InvitationCoreController_findById"];
        put?: never;
        post?: never;
        delete: operations["InvitationCoreController_revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InvitationCoreController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/personal-invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PersonalInvitationCoreController_findProjectPersonalInvitations"];
        put?: never;
        post: operations["PersonalInvitationCoreController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/personal-invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PersonalInvitationCoreController_findMyPersonalInvitations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personal-invitations/{personalInvitationId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PersonalInvitationCoreController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personal-invitations/{personalInvitationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["PersonalInvitationCoreController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personal-invitations/{personalInvitationId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PersonalInvitationCoreController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GithubAuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GoogleAuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/device-flow/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DeviceFlowController_streamMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/device-flow/send-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeviceFlowController_sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/local/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LocalAuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RefreshTokenCoreController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RefreshTokenCoreController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-connections/github/installations/{installationEntityId}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GithubExternalConnectionCoreController_getRepositoriesAvailableForInstallation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-connections/github/installations/{installationEntityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GithubExternalConnectionCoreController_getInstallationById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/external-connections/github/installations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GithubExternalConnectionCoreController_getCurrentUserInstallations"];
        put?: never;
        post: operations["GithubExternalConnectionCoreController_createInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/external-connections/github/local-mock/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GithubExternalConnectionCoreController_getLocalGithubMockBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-connections/github/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GithubExternalConnectionCoreController_createIntegration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/external-connections/github/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GithubExternalConnectionCoreController_getProjectIntegrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/external-connections/github/integrations/{integrationId}/access-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GithubExternalConnectionCoreController_getInstallationAccessToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-connections/github/integrations/{integrationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["GithubExternalConnectionCoreController_deleteIntegration"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GithubExternalConnectionCoreController_handleGithubWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BlogCoreController_findAll"];
        put?: never;
        post: operations["BlogCoreController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/posts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BlogCoreController_findBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["BlogCoreController_delete"];
        options?: never;
        head?: never;
        patch: operations["BlogCoreController_update"];
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StatsController_getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProjectCreationDefaultsSerialized: {
            /** @enum {string} */
            revealOn: "always" | "hover" | "never";
        };
        UserSerialized: {
            id: string;
            email?: string;
            avatarUrl: string;
            displayName: string;
            publicKey?: string;
            /** @enum {string} */
            authMethod: "google" | "github" | "local";
            privateKeyEncrypted?: string;
            projectCreationDefaults: components["schemas"]["ProjectCreationDefaultsSerialized"];
            isAdmin: boolean;
        };
        ProjectCreationDefaultsBody: {
            /** @enum {string} */
            revealOn: "always" | "hover" | "never";
        };
        UpdateUserBody: {
            displayName?: string;
            publicKey?: string;
            privateKeyEncrypted?: string;
            projectsOrder?: string[];
            projectCreationDefaults?: components["schemas"]["ProjectCreationDefaultsBody"];
        };
        GetPublicKeysBody: {
            userIds: string[];
        };
        GetPublicKeysResponse: {
            publicKeys: {
                [key: string]: string;
            };
        };
        ProjectMemberSerialized: {
            id: string;
            email?: string;
            avatarUrl: string;
            displayName: string;
            publicKey?: string;
            /** @enum {string} */
            role: "read" | "write" | "admin";
        };
        ProjectSettingsSerialized: {
            /** @enum {string} */
            revealOn: "always" | "hover" | "never";
        };
        ProjectSerialized: {
            id: string;
            name: string;
            members: components["schemas"]["ProjectMemberSerialized"][];
            encryptedSecretsKeys: Record<string, never>;
            encryptedSecrets: string;
            settings: components["schemas"]["ProjectSettingsSerialized"];
            createdAt: string;
            updatedAt: string;
        };
        ProjectSearchResponse: {
            id: string;
            name: string;
            encryptedSecretsKeys: Record<string, never>;
            encryptedSecrets: string;
        };
        ProjectSettingsBody: {
            /** @enum {string} */
            revealOn: "always" | "hover" | "never";
        };
        CreateProjectBody: {
            name: string;
            encryptedSecrets: string;
            encryptedSecretsKeys: Record<string, never>;
            settings: components["schemas"]["ProjectSettingsBody"];
        };
        UserPartialSerialized: {
            id: string;
            email?: string;
            avatarUrl: string;
            displayName: string;
            publicKey?: string;
        };
        ProjectSecretsVersionSerialized: {
            id: string;
            author: components["schemas"]["UserPartialSerialized"];
            encryptedSecrets: string;
            createdAt: string;
            updatedAt: string;
        };
        UpdateProjectBody: {
            name?: string;
            encryptedSecrets?: string;
            settings?: components["schemas"]["ProjectSettingsBody"];
        };
        AddEncryptedSecretsKeyBody: {
            userId: string;
            encryptedSecretsKey: string;
        };
        UpdateMemberRoleBody: {
            /** @enum {string} */
            role: "read" | "write" | "admin";
        };
        InvitationSerialized: {
            id: string;
            projectId: string;
            author: components["schemas"]["UserPartialSerialized"];
            /** @enum {string} */
            role: "read" | "write" | "admin";
            temporaryPublicKey: string;
            temporaryPrivateKey: string;
            temporarySecretsKey: string;
            createdAt: string;
        };
        CreateInvitationBody: {
            projectId: string;
            temporaryPublicKey: string;
            temporaryPrivateKey: string;
            temporarySecretsKey: string;
            /** @enum {string} */
            role: "read" | "write" | "admin";
        };
        AcceptInvitationBody: {
            newSecretsKey: string;
        };
        PersonalInvitationSerialized: {
            id: string;
            projectId: string;
            projectName: string;
            author: components["schemas"]["UserPartialSerialized"];
            invitedUser: components["schemas"]["UserPartialSerialized"];
            /** @enum {string} */
            role: "read" | "write" | "admin";
            createdAt: string;
        };
        CreatePersonalInvitationBody: {
            invitedUserId: string;
            /** @enum {string} */
            role: "read" | "write" | "admin";
        };
        GithubLoginBody: {
            githubCode: string;
        };
        TokenResponse: {
            token: string;
            refreshToken?: string;
            isNewUser?: boolean;
        };
        GoogleLoginBody: {
            googleCode: string;
            forceLocalLogin: boolean;
        };
        SendMessageBody: {
            deviceId: string;
            message: Record<string, never>;
        };
        LocalLoginBody: {
            email: string;
        };
        RefreshBody: {
            refreshToken: string;
        };
        GithubRepositorySerialized: {
            id: number;
            owner: string;
            avatarUrl: string;
            name: string;
            url: string;
            isPrivate: boolean;
        };
        CreateGithubInstallationBody: {
            githubInstallationId: number;
        };
        GithubInstallationLiveDataSerialized: {
            owner: string;
            avatar: string;
        };
        GithubInstallationSerialized: {
            id: string;
            userId: string;
            githubInstallationId: number;
            liveData: components["schemas"]["GithubInstallationLiveDataSerialized"];
            createdAt: string;
            updatedAt: string;
        };
        CreateGithubIntegrationBody: {
            repositoryId: number;
            installationEntityId: string;
            projectId: string;
        };
        GithubIntegrationSerialized: {
            id: string;
            projectId: string;
            githubRepositoryId: number;
            githubRepositoryPublicKey: string;
            githubRepositoryPublicKeyId: string;
            installationEntityId: string;
            repositoryData: Record<string, never>;
            createdAt: string;
            updatedAt: string;
        };
        InstallationPayload: {
            id: number;
        };
        GithubWebhookBody: {
            action: string;
            installation?: components["schemas"]["InstallationPayload"];
        };
        BlogPostSerialized: {
            id: string;
            title: string;
            slug: string;
            content: string;
            excerpt?: string;
            coverImageUrl?: string;
            author: components["schemas"]["UserPartialSerialized"];
            createdAt: string;
            updatedAt: string;
        };
        CreateBlogPostBody: {
            title: string;
            content: string;
            excerpt?: string;
            coverImageUrl?: string;
            slug?: string;
            createdAt?: string;
        };
        UpdateBlogPostBody: {
            title?: string;
            content?: string;
            excerpt?: string;
            coverImageUrl?: string;
            slug?: string;
            createdAt?: string;
        };
        StatsResponse: {
            users: number;
            projects: number;
            diffs: number;
            stars: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UserCoreController_readCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSerialized"];
                };
            };
        };
    };
    UserCoreController_updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSerialized"];
                };
            };
        };
    };
    UserCoreController_deleteKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserCoreController_getPublicKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetPublicKeysBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPublicKeysResponse"];
                };
            };
        };
    };
    ProjectCoreController_streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectCoreController_findUserProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSerialized"][];
                };
            };
        };
    };
    ProjectCoreController_findUserProjectsForSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSearchResponse"][];
                };
            };
        };
    };
    ProjectCoreController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSerialized"];
                };
            };
        };
    };
    ProjectCoreController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSerialized"];
                };
            };
        };
    };
    ProjectCoreController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectCoreController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSerialized"];
                };
            };
        };
    };
    ProjectCoreController_getSuggestedUsers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPartialSerialized"][];
                };
            };
        };
    };
    ProjectCoreController_findHistoryById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSecretsVersionSerialized"][];
                };
            };
        };
    };
    ProjectCoreController_addEncryptedSecretsKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddEncryptedSecretsKeyBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectCoreController_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectCoreController_updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRoleBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitationCoreController_findProjectInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationSerialized"][];
                };
            };
        };
    };
    InvitationCoreController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationSerialized"];
                };
            };
        };
    };
    InvitationCoreController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationSerialized"];
                };
            };
        };
    };
    InvitationCoreController_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitationCoreController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationSerialized"];
                };
            };
        };
    };
    PersonalInvitationCoreController_findProjectPersonalInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalInvitationSerialized"][];
                };
            };
        };
    };
    PersonalInvitationCoreController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePersonalInvitationBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalInvitationSerialized"];
                };
            };
        };
    };
    PersonalInvitationCoreController_findMyPersonalInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalInvitationSerialized"][];
                };
            };
        };
    };
    PersonalInvitationCoreController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                personalInvitationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalInvitationSerialized"];
                };
            };
        };
    };
    PersonalInvitationCoreController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                personalInvitationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PersonalInvitationCoreController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                personalInvitationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GithubAuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GithubLoginBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    GoogleAuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    DeviceFlowController_streamMessages: {
        parameters: {
            query: {
                deviceId: string;
                role: string;
                deviceName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeviceFlowController_sendMessage: {
        parameters: {
            query: {
                role: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocalAuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalLoginBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    RefreshTokenCoreController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    RefreshTokenCoreController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GithubExternalConnectionCoreController_getRepositoriesAvailableForInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                installationEntityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubRepositorySerialized"][];
                };
            };
        };
    };
    GithubExternalConnectionCoreController_getInstallationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                installationEntityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GithubExternalConnectionCoreController_getCurrentUserInstallations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubInstallationSerialized"][];
                };
            };
        };
    };
    GithubExternalConnectionCoreController_createInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGithubInstallationBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubInstallationSerialized"];
                };
            };
        };
    };
    GithubExternalConnectionCoreController_getLocalGithubMockBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubInstallationSerialized"][];
                };
            };
        };
    };
    GithubExternalConnectionCoreController_createIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGithubIntegrationBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubIntegrationSerialized"];
                };
            };
        };
    };
    GithubExternalConnectionCoreController_getProjectIntegrations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubIntegrationSerialized"][];
                };
            };
        };
    };
    GithubExternalConnectionCoreController_getInstallationAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integrationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    GithubExternalConnectionCoreController_deleteIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integrationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GithubExternalConnectionCoreController_handleGithubWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GithubWebhookBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BlogCoreController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogPostSerialized"][];
                };
            };
        };
    };
    BlogCoreController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBlogPostBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogPostSerialized"];
                };
            };
        };
    };
    BlogCoreController_findBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogPostSerialized"];
                };
            };
        };
    };
    BlogCoreController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BlogCoreController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBlogPostBody"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogPostSerialized"];
                };
            };
        };
    };
    StatsController_getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
}
